### ISSUE TITLE
auto scroll

### ISSUE THREAD

**Issue by jacobdeleon12** [jacobdeleon12/Sceneit#99]
**Describe the bug**
 clicking on bottom button will scroll the top videos
**To Reproduce**
1. Go to bottom arrorw
2. Click on click arrow

4. See error- scrolls top one and not bottom ones

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kbub27** [comment]
Nice job on getting the auto scroll working properly and concisely.
